In [1]:
import pandas as pd
import os
import glob

In [2]:
results_path = "/home/schmied.christopher/FMP_Docs/Projects/eu_os_ecbl_qc/QC_Results/"

# USC

In [ ]:
usc_qc = pd.read_csv(os.path.join(results_path, "USC_QC_Summary.csv"))

usc_first_run = usc_qc[usc_qc["run"] == "First Run"]
usc_repeat = usc_qc[usc_qc["run"] == "Repeat"]
usc_repeat2 = usc_qc[usc_qc["run"] == "Repeat2"]
usc_first_run_reject = usc_first_run[usc_first_run["qc_summary"] == "Repeat"]

In [ ]:
# Check first run for duplicate plate IDs
duplicate_plate_ids = usc_first_run[usc_first_run.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids)

if len(duplicate_plate_ids) > 0:
    print("Duplicate plate IDs found in first run:")
    print(duplicate_plate_ids[["plate_map_name", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in first run.")

In [ ]:
duplicate_plate_ids_repeat = usc_repeat[usc_repeat.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_repeat)

if len(duplicate_plate_ids_repeat) > 0:
    print("Duplicate plate IDs found in repeat run:")
    print(duplicate_plate_ids_repeat[["plate_map_name", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in repeat run.")

In [ ]:
# After analysis we agreed on a set of repeats (labeled as repeats in run)
usc_first_run["qc_summary"] = usc_first_run["plate_map_name"].isin(usc_repeat["plate_map_name"]).map({True: "repeat", False: "pass"})

# After repeate run there was a second repeat run
usc_repeat["qc_summary"] = usc_repeat["plate_map_name"].isin(usc_repeat2["plate_map_name"]).map({True: "repeat", False: "pass"})

# I know that all plates passed in the second repeat run, so I can directly set them to pass
usc_repeat2["qc_summary"] = "pass"

usc_qc_updated = pd.concat([usc_first_run, usc_repeat, usc_repeat2], ignore_index=True)

In [ ]:
cols = ["heatmap", "cell_number", "comment", "intra_plate", "intra_batch", "inter_batch", "qc_summary"]
usc_qc_updated[cols] = usc_qc_updated[cols].apply(lambda x: x.str.lower())
usc_qc_updated.to_excel(os.path.join(results_path, "USC_QC_Summary_Updated.xlsx"), index=False)

In [ ]:
# Create table relevant for martin
usc_qc_updated_martin = usc_qc_updated.copy()
usc_qc_updated_martin["batch_date"] = pd.to_datetime(usc_qc_updated_martin["batch_date"], errors="coerce")
usc_qc_updated_martin = usc_qc_updated_martin[usc_qc_updated_martin["batch_date"].notna()]
usc_qc_updated_martin["batch_date_YYMMDD"] = usc_qc_updated_martin["batch_date"].dt.strftime("%y%m%d")
usc_qc_updated_martin["plate_ID_martin"] = usc_qc_updated_martin["plate"] + usc_qc_updated_martin["replicate"] + usc_qc_updated_martin["batch_date_YYMMDD"]

usc_qc_updated_martin_pass = usc_qc_updated_martin[usc_qc_updated_martin["qc_summary"] == "pass"]
usc_qc_updated_martin_repeat = usc_qc_updated_martin[usc_qc_updated_martin["qc_summary"] == "repeat"]

usc_qc_updated_martin_pass_reduced = usc_qc_updated_martin_pass[["plate_ID_martin", "plate_map_name", "replicate", "plate", "batch_date", "qc_summary"]]
usc_qc_updated_martin_pass_reduced["batch_date"] = usc_qc_updated_martin_pass_reduced["batch_date"].dt.strftime("%Y-%m-%d")
usc_qc_updated_martin_repeat_reduced = usc_qc_updated_martin_repeat[["plate_ID_martin", "plate_map_name", "replicate", "plate", "batch_date", "qc_summary"]]
usc_qc_updated_martin_repeat_reduced["batch_date"] = usc_qc_updated_martin_repeat_reduced["batch_date"].dt.strftime("%Y-%m-%d")

# get only the plate IDs for martin
usc_qc_updated_martin_pass_reduced.to_excel(os.path.join(results_path, "USC_QC_Pass_Plate_IDs_Martin.xlsx"), index=False)
usc_qc_updated_martin_repeat_reduced.to_excel(os.path.join(results_path, "USC_QC_Rejects_Plate_IDs_Martin.xlsx"), index=False)

# MEDINA

In [ ]:
medina_qc = pd.read_csv(os.path.join(results_path, "MEDINA_QC_Summary.csv"))

In [ ]:
medina_first_run = medina_qc[medina_qc["run"] == "First Run"]
medina_second_run = medina_qc[medina_qc["run"] == "Second Run"]

medina_all_runs = medina_qc[medina_qc["run"].isin(["First Run", "Second Run"])]

medina_repeat = medina_qc[medina_qc["run"] == "Repeat"]
medina_unclear = medina_qc[medina_qc["run"] == "Unclear"]

medina_all_runs_rejects = medina_all_runs[medina_all_runs["qc_summary"] == "Repeat"]

In [ ]:
# Check first run for duplicate plate IDs
duplicate_plate_ids_first_run = medina_first_run[medina_first_run.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_first_run)

if len(duplicate_plate_ids_first_run) > 0:
    print("Duplicate plate IDs found in first run:")
    print(duplicate_plate_ids[["plate_map_name", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in first run.")

In [ ]:
# Check first run for duplicate plate IDs
duplicate_plate_ids_second_run = medina_second_run[medina_second_run.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_second_run)

if len(duplicate_plate_ids_second_run) > 0:
    print("Duplicate plate IDs found in second run:")
    print(duplicate_plate_ids_second_run[["plate_map_name", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in second run.")

In [ ]:
# Check first run for duplicate plate IDs
duplicate_plate_ids_all_runs = medina_all_runs[medina_all_runs.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_all_runs)

if len(duplicate_plate_ids_all_runs) > 0:
    print("Duplicate plate IDs found in all runs:")
    print(duplicate_plate_ids_all_runs[["plate_map_name", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in all runs.")

In [ ]:
# Check first run for duplicate plate IDs
duplicate_plate_ids_repeat = medina_repeat[medina_repeat.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_repeat)

if len(duplicate_plate_ids_repeat) > 0:
    print("Duplicate plate IDs found in repeat run:")
    print(duplicate_plate_ids_repeat[["plate_map_name", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in repeat run.")

In [ ]:
# After analysis we agreed on a set of repeats (labeled as repeats in run)
medina_all_runs["qc_summary"] = medina_all_runs["plate_map_name"].isin(medina_repeat["plate_map_name"]).map({True: "repeat", False: "pass"})

In [ ]:
# I know that all plates passed in the second repeat run, so I can directly set them to pass
medina_repeat["qc_summary"] = "pass"

In [ ]:
medina_qc_updated = pd.concat([medina_all_runs, medina_repeat, medina_unclear], ignore_index=True)

In [ ]:
cols = ["heatmap", "cell_number", "intra_plate", "intra_batch", "inter_batch", "qc_summary"]
medina_qc_updated[cols] = medina_qc_updated[cols].apply(lambda x: x.str.lower())
medina_qc_updated.to_excel(os.path.join(results_path, "Medina_QC_Summary_Updated.xlsx"), index=False)

In [ ]:
# Create table relevant for martin
medina_qc_updated_martin = medina_qc_updated.copy()
medina_qc_updated_martin["batch_date"] = pd.to_datetime(medina_qc_updated_martin["batch_date"], errors="coerce")
medina_qc_updated_martin = medina_qc_updated_martin[medina_qc_updated_martin["batch_date"].notna()]
medina_qc_updated_martin["batch_date_YYMMDD"] = medina_qc_updated_martin["batch_date"].dt.strftime("%y%m%d")
medina_qc_updated_martin["plate_ID_martin"] = medina_qc_updated_martin["plate"] + medina_qc_updated_martin["replicate"] + medina_qc_updated_martin["batch_date_YYMMDD"]

medina_qc_updated_martin_pass = medina_qc_updated_martin[medina_qc_updated_martin["qc_summary"] == "pass"]
medina_qc_updated_martin_repeat = medina_qc_updated_martin[medina_qc_updated_martin["qc_summary"] == "repeat"]

medina_qc_updated_martin_pass_reduced = medina_qc_updated_martin_pass[["plate_ID_martin", "plate_map_name", "replicate", "plate", "batch_date", "qc_summary"]]
medina_qc_updated_martin_pass_reduced["batch_date"] = medina_qc_updated_martin_pass_reduced["batch_date"].dt.strftime("%Y-%m-%d")
medina_qc_updated_martin_repeat_reduced = medina_qc_updated_martin_repeat[["plate_ID_martin", "plate_map_name", "replicate", "plate", "batch_date", "qc_summary"]]
medina_qc_updated_martin_repeat_reduced["batch_date"] = medina_qc_updated_martin_repeat_reduced["batch_date"].dt.strftime("%Y-%m-%d")

# get only the plate IDs for martin
medina_qc_updated_martin_pass_reduced.to_excel(os.path.join(results_path, "Medina_QC_Pass_Plate_IDs_Martin.xlsx"), index=False)
medina_qc_updated_martin_repeat_reduced.to_excel(os.path.join(results_path, "Medina_QC_Rejects_Plate_IDs_Martin.xlsx"), index=False)

# IMTM

In [ ]:
imtm_qc = pd.read_csv(os.path.join(results_path, "IMTM_QC_Summary.csv"))

In [ ]:
# First split dataset into plates that stick to first run, repeat and repeat 2 logic
# Separate out the plates that had the positive control issue. 
# DataFrame with the specific note
imtm_swapped = imtm_qc[imtm_qc["note"] == "Swapped wells for positive controls"]

# DataFrame with everything else (including NaN or other notes)
imtm_other = imtm_qc[imtm_qc["note"] != "Swapped wells for positive controls"]

In [ ]:
imtm_first_run = imtm_other[imtm_other["run"] == "First Run"]
imtm_repeat = imtm_other[imtm_other["run"] == "Repeat"]
imtm_repeat2 = imtm_other[imtm_other["run"] == "Repeat2"]
imtm_first_run_reject = imtm_first_run[imtm_first_run["qc_summary"] == "Repeat"]

In [ ]:
# Check first run for duplicate plate IDs
duplicate_plate_ids = imtm_first_run[imtm_first_run.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids)

if len(duplicate_plate_ids) > 0:
    print("Duplicate plate IDs found in first run:")
    print(duplicate_plate_ids[["plate_map_name", "batch_date","qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in first run.")

In [ ]:
duplicate_plate_ids_repeat = imtm_repeat[imtm_repeat.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_repeat)

if len(duplicate_plate_ids_repeat) > 0:
    print("Duplicate plate IDs found in repeat run:")
    print(duplicate_plate_ids_repeat[["plate_map_name", "batch_date", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in repeat run.")

In [ ]:
duplicate_plate_ids_repeat2 = imtm_repeat2[imtm_repeat2.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_repeat2)

if len(duplicate_plate_ids_repeat2) > 0:
    print("Duplicate plate IDs found in repeat run:")
    print(duplicate_plate_ids_repeat2[["plate_map_name", "batch_date", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in repeat2 run.")

In [ ]:
# The swapped thing should contain already all conclusion that are input manually
# For the others I need to add the qc conclusion now programattically.

In [ ]:
# After analysis we agreed on a set of repeats (labeled as repeats in run)
imtm_first_run["qc_summary"] = imtm_first_run["plate_map_name"].isin(imtm_repeat["plate_map_name"]).map({True: "repeat", False: "pass"})

# After repeate run there was a second repeat run
imtm_repeat["qc_summary"] = imtm_repeat["plate_map_name"].isin(imtm_repeat2["plate_map_name"]).map({True: "repeat", False: "pass"})

# I know that all plates passed in the second repeat run, so I can directly set them to pass
imtm_repeat2["qc_summary"] = "pass"

imtm_qc_updated = pd.concat([imtm_first_run, imtm_repeat, imtm_repeat2], ignore_index=True)

In [ ]:
# we add back the plates with swapped positive control wells, which were all labeled as repeat manually
imtm_qc_final = pd.concat([imtm_qc_updated, imtm_swapped], ignore_index=True)

In [ ]:
# harmonize content of columns all lowercase
cols = ["heatmap", "cell_number", "cell_number_comment", "intra_plate", "intra_batch", "inter_batch", "qc_summary"]
imtm_qc_final[cols] = imtm_qc_final[cols].apply(lambda x: x.str.lower())
imtm_qc_final.to_excel(os.path.join(results_path, "IMTM_QC_Summary_Updated.xlsx"), index=False)

In [ ]:
# Create table relevant for martin
imtm_qc_updated_martin = imtm_qc_final.copy()
imtm_qc_updated_martin["batch_date"] = pd.to_datetime(imtm_qc_updated_martin["batch_date"], errors="coerce")
imtm_qc_updated_martin = imtm_qc_updated_martin[imtm_qc_updated_martin["batch_date"].notna()]
imtm_qc_updated_martin["batch_date_YYMMDD"] = imtm_qc_updated_martin["batch_date"].dt.strftime("%y%m%d")
imtm_qc_updated_martin["plate_ID_martin"] = imtm_qc_updated_martin["plate"] + imtm_qc_updated_martin["replicate"] + imtm_qc_updated_martin["batch_date_YYMMDD"]

imtm_qc_updated_martin_pass = imtm_qc_updated_martin[imtm_qc_updated_martin["qc_summary"] == "pass"]
imtm_qc_updated_martin_pass_reduced = imtm_qc_updated_martin_pass[["plate_ID_martin", "plate_map_name", "replicate", "plate", "batch_date", "qc_summary"]]
imtm_qc_updated_martin_pass_reduced["batch_date"] = imtm_qc_updated_martin_pass_reduced["batch_date"].dt.strftime("%Y-%m-%d")

# get only the plate IDs for martin
imtm_qc_updated_martin_pass_reduced.to_excel(os.path.join(results_path, "IMTM_QC_Pass_Plate_IDs_Martin.xlsx"), index=False)

In [ ]:
# For IMTM there are two more categories: reject and shelfed
imtm_qc_updated_martin_repeat = imtm_qc_updated_martin[
    imtm_qc_updated_martin["qc_summary"].isin(["repeat", "reject", "shelfed"])
]
imtm_qc_updated_martin_repeat_reduced = imtm_qc_updated_martin_repeat[["plate_ID_martin", "plate_map_name", "replicate", "plate", "batch_date", "qc_summary"]]
imtm_qc_updated_martin_repeat_reduced["batch_date"] = imtm_qc_updated_martin_repeat_reduced["batch_date"].dt.strftime("%Y-%m-%d")

imtm_qc_updated_martin_repeat_reduced.to_excel(os.path.join(results_path, "IMTM_QC_Rejects_Plate_IDs_Martin.xlsx"), index=False)

# FMP

In [6]:
fmp_qc = pd.read_csv(
    os.path.join(results_path, "FMP_QC_Summary2.csv"))

In [7]:
fmp_qc.head()

,plate_map_name,plate,replicate,batch_date,run,site_qc,note_experiment,heatmap_visible_artifacts,heatmap,cell_number,cell_number_comment,intra_plate,intra_batch,inter_batch,qc_summary,note
0,C1084_R1,C1084,R1,2024-06-05,First Run,y,NaN,strong rim effect mito,pass,Fail,NaN,Pass,Pass,Flag,Repeat,"Plate do not match later dates, incorrect batc..."
1,C1085_R1,C1085,R1,2024-06-05,First Run,y,NaN,rim effect mito,pass,Fail,NaN,Flag,Flag,Flag,Repeat,Plate do not match later dates
2,C1086_R1,C1086,R1,2024-06-05,First Run,y,NaN,rim effect mito,pass,Fail,NaN,Pass,Pass,Flag,Repeat,Plate do not match later dates
3,C1087_R1,C1087,R1,2024-06-05,First Run,y,NaN,rim effect mito,pass,Fail,NaN,Pass,Pass,Flag,Repeat,Plate do not match later dates
4,C1088_R1,C1088,R1,2024-06-05,First Run,y,NaN,rim effect mito,pass,Fail,NaN,Pass,Pass,Flag,Repeat,Plate do not match later dates

In [8]:
fmp_first_run = fmp_qc[fmp_qc["run"] == "First Run"]
fmp_repeat = fmp_qc[fmp_qc["run"] == "Repeat"]
fmp_repeat2 = fmp_qc[fmp_qc["run"] == "Repeat2"]

In [9]:
# Check first run for duplicate plate IDs
duplicate_plate_ids = fmp_first_run[fmp_first_run.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids)

if len(duplicate_plate_ids) > 0:
    print("Duplicate plate IDs found in first run:")
    print(duplicate_plate_ids[["plate_map_name", "batch_date","qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in first run.")

No duplicate plate IDs found in first run.

In [10]:
duplicate_plate_ids_repeat = fmp_repeat[fmp_repeat.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_repeat)

if len(duplicate_plate_ids_repeat) > 0:
    print("Duplicate plate IDs found in repeat run:")
    print(duplicate_plate_ids_repeat[["plate_map_name", "batch_date", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in repeat run.")

No duplicate plate IDs found in repeat run.

In [11]:
duplicate_plate_ids_repeat2 = fmp_repeat2[fmp_repeat2.duplicated(subset="plate_map_name", keep=False)]
len(duplicate_plate_ids_repeat2)

if len(duplicate_plate_ids_repeat2) > 0:
    print("Duplicate plate IDs found in repeat run:")
    print(duplicate_plate_ids_repeat2[["plate_map_name", "batch_date", "qc_summary", "run"]])
else:
    print("No duplicate plate IDs found in repeat2 run.")

No duplicate plate IDs found in repeat2 run.

In [12]:
# harmonize content of columns all lowercase
cols = ["heatmap", "cell_number", "cell_number_comment", "intra_plate", "intra_batch", "inter_batch", "qc_summary"]
fmp_qc [cols] = fmp_qc [cols].apply(lambda x: x.str.lower())
fmp_qc.to_excel(os.path.join(results_path, "FMP_QC_Summary_Updated.xlsx"), index=False)

In [13]:
# Filter out any all failed and repeated plates only get the passed. 
fmp_qc_pass = fmp_qc[fmp_qc["qc_summary"] == "pass"]

In [14]:
fmp_qc_pass.head()

,plate_map_name,plate,replicate,batch_date,run,site_qc,note_experiment,heatmap_visible_artifacts,heatmap,cell_number,cell_number_comment,intra_plate,intra_batch,inter_batch,qc_summary,note
50,FMP01_R1,FMP01,R1,2024-07-10,First Run,y,NaN,rim effect mito,pass,pass,NaN,pass,NaN,flag,pass,NaN
51,C1094_R2,C1094,R2,2024-07-10,First Run,y,NaN,weak rim effect mito,pass,pass,NaN,pass,pass,fail,pass,NaN
52,C1095_R2,C1095,R2,2024-07-10,First Run,y,NaN,weak rim effect mito,pass,pass,NaN,pass,pass,fail,pass,NaN
53,C1096_R2,C1096,R2,2024-07-10,First Run,y,NaN,weak rim effect mito,pass,pass,NaN,pass,pass,fail,pass,NaN
54,C1097_R2,C1097,R2,2024-07-10,First Run,y,NaN,NaN,pass,pass,NaN,pass,pass,fail,pass,NaN

In [15]:
# this is the file that contains all the IDs that should be done
fmp_ids = pd.read_csv(os.path.join(results_path, "FMP_allIDs.csv"))

In [16]:
# Remove positive control plates with FMP string in plate name
fmp_qc_pass_filtered = fmp_qc_pass[~fmp_qc_pass["plate"].str.contains("FMP", na=False)]

In [17]:
# Then remove any duplicates
fmp_qc_final_filtered_unique = fmp_qc_pass_filtered.drop_duplicates(subset="plate_map_name")

In [18]:
cols = ["plate_map_name", "plate", "replicate"]

diff = (
    fmp_ids.merge(
        fmp_qc_final_filtered_unique,
        on=cols,
        how="left",
        indicator=True
    )
    .query('_merge == "left_only"')
    .drop(columns="_merge")
)

In [19]:
diff.to_excel(os.path.join(results_path, "FMP_QC_Summary_todo.xlsx"), index=False)

In [20]:
len(diff)

70

In [21]:
len(fmp_qc_final_filtered_unique)

222

In [22]:
len(fmp_ids)

292